'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';

const SOCIALS = [['TELEGRAM','https://t.me/Roninoffical'],['INSTAGRAM','https://www.instagram.com/roninonchain?stkn=MWcwNXNjZmpqNTRkNQ%3D%3D'],['DISCORD','https://discord.gg/P22zCvBmz'],['REDDIT','https://reddit.com/u/RoninOnChain/s/IYkES207VR'],['YOUTUBE','https://www.youtube.com/@RoninOnChain']] as const;
const TIERS=[{name:'OPEN CIRCLE',price:'$0',cadence:'forever',tone:'green',points:['Community access','RONIN philosophy & research','Public announcements','No fabricated signals','Core market analysis']},{name:'VANGUARD',price:'$79',cadence:'/ month',tone:'silver',points:['24/7 intelligence access','Faster processing','Stronger verification','Priority alerts','Detailed intelligence receipts','Greater coverage']},{name:'WARDEN',price:'$199',cadence:'/ month',tone:'gold',points:['Everything in Vanguard','Deep intelligence','Advanced wallet intelligence','Continuous ranking','Deeper verification','Continuous analysis']},{name:'SHOGUN',price:'$499',cadence:'/ month',tone:'red',points:['Everything in Warden','Maximum priority','Deepest verification','Independent validation','Strongest available intelligence','Priority processing']}] as const;
const METHOD=['SCAN','DISCOVER','QUALIFY','UNDERSTAND','VERIFY','PREDICT','RECORD','TRACK','RESOLVE','LEARN'];
const FAQ=[['What is RONIN?','RONIN is an on-chain intelligence service built around discovery, qualification, verification, prediction, tracking, and measured learning.'],['Where is intelligence delivered?','Telegram is the delivery layer. The website is the public front door for the mission, methodology, access levels, and community.'],['Does RONIN guarantee returns?','No. RONIN does not guarantee profits, returns, accuracy, or outcomes. Crypto is high risk.'],['Why can RONIN say no?','A disciplined system needs an abstention state. If evidence is insufficient or contradictory, there may be no valid prediction.'],['How does founding access work?','The first 50 Open Circle members join free. After member 50, Open Circle becomes a one-time $1 joining fee.'],['Is RONIN financial advice?','No. RONIN is an intelligence and research service. Users remain responsible for their own decisions and risk.']];

export default function HomePage(){
 const [menu,setMenu]=useState(false),[faq,setFaq]=useState<number|null>(0),[modal,setModal]=useState<{type:'telegram'|'external';label:string;href:string}|null>(null),[accepted,setAccepted]=useState(false),[privacy,setPrivacy]=useState(true);
 useEffect(()=>setPrivacy(localStorage.getItem('ronin-privacy-choice')==='minimal'),[]);
 const telegram=(label='JOIN RONIN')=>{setAccepted(false);setModal({type:'telegram',label,href:'https://t.me/Roninoffical'})};
 return <div className="site">
  <header className="header"><div className="nav shell-wide"><a className="brand" href="#top" aria-label="RONIN home"><span className="brand-kanji">浪</span><span>RONIN</span></a><nav className={menu?'nav-links open':'nav-links'} aria-label="Primary">{['HOME','INTELLIGENCE','TIERS','ABOUT','FAQ','CONTACT'].map(x=><a key={x} href={'#'+x.toLowerCase()} onClick={()=>setMenu(false)}>{x}</a>)}</nav><div className="nav-actions"><a className="outline-btn" href="#tiers">ACCESS</a><button className="green-btn" onClick={()=>telegram()}>JOIN RONIN <span>→</span></button></div><button className="menu-toggle" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}><span/><span/><span/></button></div></header>
  <main id="top">
   <section className="hero" id="home"><img src="/media/ronin-visual-suite.webp" alt="RONIN supplied interface visual"/><div className="hero-overlay"/><div className="hero-copy shell"><p className="kicker">RONIN // ALPHA INTELLIGENCE</p><h1>INTELLIGENCE<br/><span>BEFORE THE CROWD_</span></h1><p>Real-time on-chain intelligence.<br/>Earlier context. Better evidence.<br/>Built for people who want the signal without the noise.</p><div className="actions"><button className="green-btn large" onClick={()=>telegram()}>JOIN RONIN <span>→</span></button><a className="outline-btn large" href="#intelligence">VIEW INTELLIGENCE <span>→</span></a></div><div className="hero-stats"><span><b>REAL-TIME</b>ON-CHAIN DATA</span><span><b>RESEARCH</b>STRUCTURED EVIDENCE</span><span><b>VERIFICATION</b>INDEPENDENT CHECKS</span><span><b>GLOBAL</b>RONIN COMMUNITY</span></div></div><div className="kanji-rail">先を行く者だけの世界</div></section>
   <section className="visual-strip shell"><img src="/media/ronin-visual-suite.webp" alt="RONIN supplied home, tiers, methodology, edge and mobile interface visuals"/></section>
   <section id="intelligence" className="section shell"><div className="section-heading"><div><p className="kicker">RONIN // INTELLIGENCE</p><h2>SEE WHAT<br/><span>THE NOISE HIDES.</span></h2></div><p>RONIN turns on-chain activity into structured intelligence. The public site explains the system; detailed member intelligence is delivered through the official Telegram channel.</p></div><div className="dashboard-frame"><div className="frame-top"><span>RONIN INTELLIGENCE TERMINAL</span><span>SUPPLIED VISUAL / NO LIVE CLAIMS</span></div><img src="/media/ronin-intelligence-dashboard.webp" alt="RONIN supplied dashboard showing charts, market intelligence, sentiment and wallet intelligence"/></div><div className="intel-grid"><article><b>01</b><h3>DATA OVER HYPE.</h3><p>Raw activity is treated as evidence, not decoration.</p></article><article><b>02</b><h3>EVIDENCE OVER PROMISES.</h3><p>Weak or contradictory information can result in no valid output.</p></article><article><b>03</b><h3>EVERY OUTPUT LEAVES A RECEIPT.</h3><p>Predictions are designed to be measurable after delivery.</p></article><article className="gold-card"><b>04</b><h3>TELEGRAM IS THE DELIVERY LAYER.</h3><p>Members receive detailed intelligence through the official channel.</p></article></div></section>
   <section id="about" className="section shell about"><div className="section-heading"><div><p className="kicker gold">MORE THAN SIGNALS</p><h2>A HIGHER<br/><span className="gold-text">STANDARD.</span></h2></div><p>RONIN is a research engine and community built around observation, analysis, verification, prediction, tracking, and learning.</p></div><div className="edge-image"><img src="/media/ronin-visual-suite.webp" alt="RONIN supplied edge and methodology visual"/></div><div className="edge-grid"><div><b>REAL-TIME</b><span>On-chain monitoring</span></div><div><b>VERIFIED</b><span>Independent confirmation</span></div><div><b>TRACEABLE</b><span>Prediction receipts</span></div><div><b>RESPONSIBLE</b><span>No guaranteed returns</span></div></div></section>
   <section id="method" className="method shell"><div className="method-copy"><p className="kicker gold">THE RONIN METHODOLOGY</p><h2>DISCIPLINE<br/><span className="gold-text">FUELS FREEDOM.</span></h2><div className="method-grid">{METHOD.map((x,i)=><div key={x}><b>{String(i+1).padStart(2,'0')}</b><strong>{x}</strong></div>)}</div><p className="method-note">DATA OVER HYPE. EVIDENCE OVER PROMISES. NO FABRICATED SIGNALS.</p></div></section>
   <section id="tiers" className="section shell tiers"><div className="section-heading centered"><div><p className="kicker">ACCESS LEVELS</p><h2>CHOOSE YOUR <span>PATH.</span></h2></div><p>Different levels of coverage, verification depth and processing priority. Membership never guarantees an outcome.</p></div><div className="tier-grid">{TIERS.map((tier,i)=><article key={tier.name} className={'tier '+tier.tone}><div className="tier-number">0{i+1}</div><div className="tier-symbol">{['浪','侍','守','将'][i]}</div><p className="tier-kicker">{i===0?'FOUNDING / COMMUNITY':i===1?'EARLY INTELLIGENCE':i===2?'DEEP INTELLIGENCE':'HIGHEST PRIORITY'}</p><h3>{tier.name}</h3><div className="tier-price">{tier.price}<small>{tier.cadence}</small></div><ul>{tier.points.map(p=><li key={p}>◆ {p}</li>)}</ul><button className="tier-btn" onClick={()=>telegram(tier.name+' ACCESS')}>{i===0?'JOIN FREE':'GET '+tier.name} <span>→</span></button></article>)}</div><div className="founding"><span className="brand-kanji">浪</span><div><b>FOUNDING ACCESS</b><span>First 50 members join Open Circle free. After #50, Open Circle becomes a one-time $1 joining fee.</span></div><strong>50 <small>FOUNDING SPOTS</small></strong></div></section>
   <section id="faq" className="section shell faq"><div className="section-heading centered"><div><p className="kicker">COMMON QUESTIONS</p><h2>FREQUENTLY <span>ASKED.</span></h2></div></div>{FAQ.map(([q,a],i)=><div className={'faq-row '+(faq===i?'open':'')} key={q}><button onClick={()=>setFaq(faq===i?null:i)} aria-expanded={faq===i}><span>{q}</span><b>{faq===i?'−':'+'}</b></button>{faq===i&&<p>{a}</p>}</div>)}</section>
   <section id="contact" className="contact shell"><div><p className="kicker">THE RONIN CIRCLE</p><h2>THE WEBSITE IS THE<br/><span>FRONT DOOR.</span></h2><p>Choose your access level, review the legal pages, then continue to the official Telegram flow.</p><button className="green-btn large" onClick={()=>telegram()}>CONTINUE TO TELEGRAM <span>→</span></button></div><div className="contact-card"><b>PUBLIC BRAND</b><strong>RONIN HQ</strong><span>No personal operator identity is displayed on the public site.</span><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/cookies">Cookies</a><a href="/refunds">Refunds</a></div></section>
  </main>
  <footer className="footer shell-wide"><div><a className="brand" href="#top"><span className="brand-kanji">浪</span><span>RONIN</span></a><p>INTELLIGENCE BEFORE THE CROWD.</p></div><div className="footer-links"><b>EXPLORE</b><a href="#intelligence">Intelligence</a><a href="#tiers">Tiers</a><a href="#about">About</a><a href="#faq">FAQ</a></div><div className="footer-links"><b>LEGAL</b><Link href="/privacy">Privacy Policy</Link><Link href="/terms">Terms & Conditions</Link><Link href="/cookies">Cookie Policy</Link><Link href="/refunds">Refund Policy</Link></div><div className="footer-links"><b>SOCIAL</b>{SOCIALS.map(([label,href])=><button key={label} onClick={()=>setModal({type:'external',label,href})}>{label}</button>)}</div><div className="footer-bottom"><span>© 2026 RONIN HQ. All rights reserved.</span><span>NO GUARANTEED RETURNS. DO YOUR OWN RESEARCH.</span></div></footer>
  {!privacy&&<div className="privacy-banner" role="dialog" aria-label="Privacy notice"><div><b>PRIVACY-FIRST BY DEFAULT</b><span>No advertising cookies, analytics trackers, or third-party embeds are used by this website. Minimal local storage is used only for this notice.</span></div><button className="green-btn" onClick={()=>{localStorage.setItem('ronin-privacy-choice','minimal');setPrivacy(true)}}>ACKNOWLEDGE</button><Link href="/privacy">READ PRIVACY</Link></div>}
  {modal&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setModal(null)}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" aria-label="Close" onClick={()=>setModal(null)}>×</button>{modal.type==='telegram'?<><p className="kicker">TELEGRAM ACCESS</p><h2 id="modal-title">CONTINUE TO <span>RONIN.</span></h2><p>You are leaving RONIN HQ for the official Telegram destination. Review the legal pages before continuing.</p><label className="consent"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>I have read and accept the <Link href="/terms" target="_blank">Terms & Conditions</Link>, <Link href="/privacy" target="_blank">Privacy Policy</Link> and <Link href="/refunds" target="_blank">Refund Policy</Link>. I understand RONIN is not financial advice and does not guarantee returns.</span></label><button className="green-btn large full" disabled={!accepted} onClick={()=>window.open(modal.href,'_blank','noopener,noreferrer')}>I ACCEPT & CONTINUE <span>→</span></button></>:<><p className="kicker">EXTERNAL DESTINATION</p><h2 id="modal-title">OPEN <span>{modal.label}?</span></h2><p>You are leaving RONIN HQ for an external service. RONIN does not control that service's content, privacy practices, or availability.</p><button className="green-btn large full" onClick={()=>{window.open(modal.href,'_blank','noopener,noreferrer');setModal(null)}}>CONTINUE <span>→</span></button></>}</div></div>}
 </div>
}
